### ISSUE TITLE
Incompatible with packer > 0.7.2

### ISSUE THREAD

**Issue by simontesar** [ustream/packer-builder-lxc#12]
When trying to build packer-builder-lxc via `gox` and go 1.4.2, it fails with 
```
undefined: packer.ConfigTemplate
```
Seems to be due to changes in the Plugin API in packer 0.7.5.

**Comment by ironpinguin** [comment]
With the current master it will be compatible again. Can you please retest it.

**Comment by oker1** [comment]
It's working now.
