### ISSUE TITLE
step_wait_init doesn't wait for IP address

### ISSUE THREAD

**Issue by perj** [ustream/packer-builder-lxc#5]
It's perhaps arguable if it should, but provisioning typically requires networking, so it makes sense. It also seems like other builders do wait for an IP.

A shell command such as 

```
/sbin/ip addr show scope global | grep -wq inet
```

will exit 0 if there is an IP and != 0 if there isn't.

**Comment by ccope** [comment]
I've had to implement my own network health checking on ubuntu containers, lxc-wait has not been sufficient. This is with LXC 1.1+ on ubuntu 14.04 hosts with kernel 3.16.
